# Generated by Django 3.2.7 on 2021-10-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=1000)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_a.room')),
            ],
        ),
    ]
