# Generated by Django 3.2.7 on 2023-01-19 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sebi', '0004_alter_share_unique_id'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='bought_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='share',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sebi.share'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
