# Generated by Django 3.2.7 on 2023-01-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20230120_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='position',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intraday',
            name='position',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10),
            preserve_default=False,
        ),
    ]
