# Generated by Django 3.2.7 on 2023-01-22 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sebi', '0008_alter_share_unique_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0004_auto_20230121_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntradayActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='price',
            new_name='average_price',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='bought_on',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='position',
        ),
        migrations.RemoveField(
            model_name='intraday',
            name='bought_on',
        ),
        migrations.RemoveField(
            model_name='intraday',
            name='position',
        ),
        migrations.RemoveField(
            model_name='intraday',
            name='price',
        ),
        migrations.RemoveField(
            model_name='intraday',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='intraday',
            name='share',
        ),
        migrations.RemoveField(
            model_name='intraday',
            name='user',
        ),
        migrations.AddField(
            model_name='delivery',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DeliveryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('position', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10)),
                ('bought_on', models.DateTimeField(auto_now_add=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebi.share')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
