# Generated by Django 3.2.7 on 2023-01-24 08:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sebi', '0008_alter_share_unique_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0005_auto_20230122_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='intraday',
            name='average_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intraday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intraday',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intraday',
            name='share',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sebi.share'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intraday',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='intraday',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intraday',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 3, 30, 0, 612772)),
        ),
    ]
