# Generated by Django 3.2.7 on 2023-01-24 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20230124_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='intraday',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 3, 30, 0, 637077)),
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trade.manager')),
            ],
        ),
    ]
