# Generated by Django 3.2.7 on 2023-01-24 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20230124_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intraday',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 3, 30, 0, 74165)),
        ),
        migrations.DeleteModel(
            name='B',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
