# Generated by Django 3.2.7 on 2023-01-24 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20230124_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intraday',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 3, 30, 0, 13935)),
        ),
    ]
