# Generated by Django 3.2.7 on 2023-01-24 12:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sebi', '0008_alter_share_unique_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0009_alter_intraday_valid_till'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intraday',
            name='is_active',
        ),
        migrations.AddField(
            model_name='intraday',
            name='position',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intradayactivity',
            name='bought_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intradayactivity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intradayactivity',
            name='position',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intradayactivity',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intradayactivity',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intradayactivity',
            name='share',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sebi.share'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intradayactivity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intraday',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 3, 30, 0, 763643)),
        ),
    ]
