# Generated by Django 3.2.7 on 2023-01-31 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_alter_intraday_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intraday',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 3, 30, 0, 540988)),
        ),
    ]
