# Generated by Django 3.2.7 on 2023-01-19 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unique_id', models.UUIDField(default=uuid.UUID('56070342-cde5-484e-be85-4494b4056a7d'), editable=False)),
            ],
        ),
    ]
