# Generated by Django 3.2.7 on 2023-01-19 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sebi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('e1f9b8d4-e606-4de5-b43c-1889e71fb9f4'), editable=False, max_length=255),
        ),
    ]
