# Generated by Django 3.2.7 on 2023-01-19 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sebi', '0003_alter_share_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('26f145d0-3106-4061-b9af-2ae5f5e73eb5'), editable=False, max_length=255),
        ),
    ]
