# Generated by Django 3.2.7 on 2023-01-19 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sebi', '0004_alter_share_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('c16a2ca5-03cf-4af9-808b-8c8707e5ecc0'), editable=False, max_length=255),
        ),
    ]
