# Generated by Django 3.2.7 on 2023-01-19 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sebi', '0005_auto_20230119_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('f47767e4-9667-49ef-b0e4-a3deb7c46272'), editable=False, max_length=255, unique=True),
        ),
    ]
