# Generated by Django 3.2.7 on 2023-01-19 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sebi', '0006_alter_share_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('e877f9db-5f73-4694-9db2-1c9e328fdd04'), editable=False),
        ),
    ]
